swipe:
  3:
    left:
      command: 'xdtool set_desktop --relative -- -1'
    right:
      command: 'xdotool set_desktop --relative 1'
    up:
      command: 'xdotool key super+s'
    down:
      command: 'xdotool key super+s'
  4:
    left:
      command: 'xdptool key super+left'
    right:
      command: 'xdotool key super+right'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
    threshold: 0.1
  out:
     command: 'xdotool key ctrl+minus'
     threshold: 0.1

threshold:
  swipe: 0.3
  pinch: 0.3

interval:
  swipe: 0.1
  pinch: 0.1

