theme="catppuccin_macchiato"

[editor]
line-number="relative"
bufferline = "multiple"
color-modes = true
true-color=true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-type"]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"

[keys.normal]
A-l = "select_next_sibling"
A-h = "select_prev_sibling"
A-j = "shrink_selection"
A-k = "expand_selection"

