theme="catppuccin_macchiato"

[editor]
line-number="relative"
bufferline = "multiple"
color-modes = true
true-color=true
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "hint"
# Minimum severity to show a diagnostic on other lines:
other-lines = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-type"]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true

[keys.normal]
A-l = "select_next_sibling"
A-h = "select_prev_sibling"
A-j = "shrink_selection"
A-k = "expand_selection"

